# Generated by Django 2.2.28 on 2022-12-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.BigIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('dateChanged', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
